title: Julien DELCLOS - Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/Julien" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Julien DELCLOS # name
author-img: julien-delclos.png # photo
about-author: I am a software engineer focusing on AI, Computer Vision and Deep Learning. Always eager to keep learning. # description
social-codingame: b944cb66159c494961db183c595578915353933 # CodinGame handle
social-facebook: delclos.julien # Facebook handle
social-github: JujuDel # Github handle
social-linkedin: julien-delclos-19b292106 # Linkedin handle
social-email: julien.delclos@gmail.com # Email address

# Disqus
discus-identifier: # discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
